# fly.toml file generated for fly-varnish on 2022-02-20T15:15:41-04:00

app = "fly-varnish"


[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
