# fly.toml file generated for fly-varnish-example on 2022-02-24T22:52:49-04:00

app = "fly-varnish-example"


[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
