# fly.toml file generated for fly-varnish on 2022-02-23T08:35:54-04:00

app = "fly-varnish-example"

[mounts]
source="varnish_data"
destination="/data"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
